// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	baseproposal "github.com/IBM-Blockchain/fabric-operator/pkg/offering/base/proposal"
)

type Update struct {
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Update) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Update) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ baseproposal.Update = new(Update)
