// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/IBM-Blockchain/fabric-operator/pkg/offering/base/network"
)

type Update struct {
	MemberUpdatedStub        func() bool
	memberUpdatedMutex       sync.RWMutex
	memberUpdatedArgsForCall []struct {
	}
	memberUpdatedReturns struct {
		result1 bool
	}
	memberUpdatedReturnsOnCall map[int]struct {
		result1 bool
	}
	OrdererCreateStub        func() bool
	ordererCreateMutex       sync.RWMutex
	ordererCreateArgsForCall []struct {
	}
	ordererCreateReturns struct {
		result1 bool
	}
	ordererCreateReturnsOnCall map[int]struct {
		result1 bool
	}
	OrdererStatusUpdatedStub        func() bool
	ordererStatusUpdatedMutex       sync.RWMutex
	ordererStatusUpdatedArgsForCall []struct {
	}
	ordererStatusUpdatedReturns struct {
		result1 bool
	}
	ordererStatusUpdatedReturnsOnCall map[int]struct {
		result1 bool
	}
	SpecUpdatedStub        func() bool
	specUpdatedMutex       sync.RWMutex
	specUpdatedArgsForCall []struct {
	}
	specUpdatedReturns struct {
		result1 bool
	}
	specUpdatedReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Update) MemberUpdated() bool {
	fake.memberUpdatedMutex.Lock()
	ret, specificReturn := fake.memberUpdatedReturnsOnCall[len(fake.memberUpdatedArgsForCall)]
	fake.memberUpdatedArgsForCall = append(fake.memberUpdatedArgsForCall, struct {
	}{})
	stub := fake.MemberUpdatedStub
	fakeReturns := fake.memberUpdatedReturns
	fake.recordInvocation("MemberUpdated", []interface{}{})
	fake.memberUpdatedMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Update) MemberUpdatedCallCount() int {
	fake.memberUpdatedMutex.RLock()
	defer fake.memberUpdatedMutex.RUnlock()
	return len(fake.memberUpdatedArgsForCall)
}

func (fake *Update) MemberUpdatedCalls(stub func() bool) {
	fake.memberUpdatedMutex.Lock()
	defer fake.memberUpdatedMutex.Unlock()
	fake.MemberUpdatedStub = stub
}

func (fake *Update) MemberUpdatedReturns(result1 bool) {
	fake.memberUpdatedMutex.Lock()
	defer fake.memberUpdatedMutex.Unlock()
	fake.MemberUpdatedStub = nil
	fake.memberUpdatedReturns = struct {
		result1 bool
	}{result1}
}

func (fake *Update) MemberUpdatedReturnsOnCall(i int, result1 bool) {
	fake.memberUpdatedMutex.Lock()
	defer fake.memberUpdatedMutex.Unlock()
	fake.MemberUpdatedStub = nil
	if fake.memberUpdatedReturnsOnCall == nil {
		fake.memberUpdatedReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.memberUpdatedReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *Update) OrdererCreate() bool {
	fake.ordererCreateMutex.Lock()
	ret, specificReturn := fake.ordererCreateReturnsOnCall[len(fake.ordererCreateArgsForCall)]
	fake.ordererCreateArgsForCall = append(fake.ordererCreateArgsForCall, struct {
	}{})
	stub := fake.OrdererCreateStub
	fakeReturns := fake.ordererCreateReturns
	fake.recordInvocation("OrdererCreate", []interface{}{})
	fake.ordererCreateMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Update) OrdererCreateCallCount() int {
	fake.ordererCreateMutex.RLock()
	defer fake.ordererCreateMutex.RUnlock()
	return len(fake.ordererCreateArgsForCall)
}

func (fake *Update) OrdererCreateCalls(stub func() bool) {
	fake.ordererCreateMutex.Lock()
	defer fake.ordererCreateMutex.Unlock()
	fake.OrdererCreateStub = stub
}

func (fake *Update) OrdererCreateReturns(result1 bool) {
	fake.ordererCreateMutex.Lock()
	defer fake.ordererCreateMutex.Unlock()
	fake.OrdererCreateStub = nil
	fake.ordererCreateReturns = struct {
		result1 bool
	}{result1}
}

func (fake *Update) OrdererCreateReturnsOnCall(i int, result1 bool) {
	fake.ordererCreateMutex.Lock()
	defer fake.ordererCreateMutex.Unlock()
	fake.OrdererCreateStub = nil
	if fake.ordererCreateReturnsOnCall == nil {
		fake.ordererCreateReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.ordererCreateReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *Update) OrdererStatusUpdated() bool {
	fake.ordererStatusUpdatedMutex.Lock()
	ret, specificReturn := fake.ordererStatusUpdatedReturnsOnCall[len(fake.ordererStatusUpdatedArgsForCall)]
	fake.ordererStatusUpdatedArgsForCall = append(fake.ordererStatusUpdatedArgsForCall, struct {
	}{})
	stub := fake.OrdererStatusUpdatedStub
	fakeReturns := fake.ordererStatusUpdatedReturns
	fake.recordInvocation("OrdererStatusUpdated", []interface{}{})
	fake.ordererStatusUpdatedMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Update) OrdererStatusUpdatedCallCount() int {
	fake.ordererStatusUpdatedMutex.RLock()
	defer fake.ordererStatusUpdatedMutex.RUnlock()
	return len(fake.ordererStatusUpdatedArgsForCall)
}

func (fake *Update) OrdererStatusUpdatedCalls(stub func() bool) {
	fake.ordererStatusUpdatedMutex.Lock()
	defer fake.ordererStatusUpdatedMutex.Unlock()
	fake.OrdererStatusUpdatedStub = stub
}

func (fake *Update) OrdererStatusUpdatedReturns(result1 bool) {
	fake.ordererStatusUpdatedMutex.Lock()
	defer fake.ordererStatusUpdatedMutex.Unlock()
	fake.OrdererStatusUpdatedStub = nil
	fake.ordererStatusUpdatedReturns = struct {
		result1 bool
	}{result1}
}

func (fake *Update) OrdererStatusUpdatedReturnsOnCall(i int, result1 bool) {
	fake.ordererStatusUpdatedMutex.Lock()
	defer fake.ordererStatusUpdatedMutex.Unlock()
	fake.OrdererStatusUpdatedStub = nil
	if fake.ordererStatusUpdatedReturnsOnCall == nil {
		fake.ordererStatusUpdatedReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.ordererStatusUpdatedReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *Update) SpecUpdated() bool {
	fake.specUpdatedMutex.Lock()
	ret, specificReturn := fake.specUpdatedReturnsOnCall[len(fake.specUpdatedArgsForCall)]
	fake.specUpdatedArgsForCall = append(fake.specUpdatedArgsForCall, struct {
	}{})
	stub := fake.SpecUpdatedStub
	fakeReturns := fake.specUpdatedReturns
	fake.recordInvocation("SpecUpdated", []interface{}{})
	fake.specUpdatedMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Update) SpecUpdatedCallCount() int {
	fake.specUpdatedMutex.RLock()
	defer fake.specUpdatedMutex.RUnlock()
	return len(fake.specUpdatedArgsForCall)
}

func (fake *Update) SpecUpdatedCalls(stub func() bool) {
	fake.specUpdatedMutex.Lock()
	defer fake.specUpdatedMutex.Unlock()
	fake.SpecUpdatedStub = stub
}

func (fake *Update) SpecUpdatedReturns(result1 bool) {
	fake.specUpdatedMutex.Lock()
	defer fake.specUpdatedMutex.Unlock()
	fake.SpecUpdatedStub = nil
	fake.specUpdatedReturns = struct {
		result1 bool
	}{result1}
}

func (fake *Update) SpecUpdatedReturnsOnCall(i int, result1 bool) {
	fake.specUpdatedMutex.Lock()
	defer fake.specUpdatedMutex.Unlock()
	fake.SpecUpdatedStub = nil
	if fake.specUpdatedReturnsOnCall == nil {
		fake.specUpdatedReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.specUpdatedReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *Update) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.memberUpdatedMutex.RLock()
	defer fake.memberUpdatedMutex.RUnlock()
	fake.ordererCreateMutex.RLock()
	defer fake.ordererCreateMutex.RUnlock()
	fake.ordererStatusUpdatedMutex.RLock()
	defer fake.ordererStatusUpdatedMutex.RUnlock()
	fake.specUpdatedMutex.RLock()
	defer fake.specUpdatedMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Update) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ network.Update = new(Update)
