//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 * Copyright contributors to the Hyperledger Fabric Operator project
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 * 	  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	consolev1 "github.com/IBM-Blockchain/fabric-operator/pkg/apis/console/v1"
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddMember) DeepCopyInto(out *AddMember) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]NamespacedName, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddMember.
func (in *AddMember) DeepCopy() *AddMember {
	if in == nil {
		return nil
	}
	out := new(AddMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CAAction) DeepCopyInto(out *CAAction) {
	*out = *in
	out.Renew = in.Renew
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CAAction.
func (in *CAAction) DeepCopy() *CAAction {
	if in == nil {
		return nil
	}
	out := new(CAAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CAConnectionProfile) DeepCopyInto(out *CAConnectionProfile) {
	*out = *in
	out.Endpoints = in.Endpoints
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(ConnectionProfileTLS)
		**out = **in
	}
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = new(MSP)
		(*in).DeepCopyInto(*out)
	}
	if in.TLSCA != nil {
		in, out := &in.TLSCA, &out.TLSCA
		*out = new(MSP)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CAConnectionProfile.
func (in *CAConnectionProfile) DeepCopy() *CAConnectionProfile {
	if in == nil {
		return nil
	}
	out := new(CAConnectionProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CACustomNames) DeepCopyInto(out *CACustomNames) {
	*out = *in
	out.PVC = in.PVC
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CACustomNames.
func (in *CACustomNames) DeepCopy() *CACustomNames {
	if in == nil {
		return nil
	}
	out := new(CACustomNames)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CAEndpoints) DeepCopyInto(out *CAEndpoints) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CAEndpoints.
func (in *CAEndpoints) DeepCopy() *CAEndpoints {
	if in == nil {
		return nil
	}
	out := new(CAEndpoints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CAImages) DeepCopyInto(out *CAImages) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CAImages.
func (in *CAImages) DeepCopy() *CAImages {
	if in == nil {
		return nil
	}
	out := new(CAImages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CAPVCNames) DeepCopyInto(out *CAPVCNames) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CAPVCNames.
func (in *CAPVCNames) DeepCopy() *CAPVCNames {
	if in == nil {
		return nil
	}
	out := new(CAPVCNames)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CAReference) DeepCopyInto(out *CAReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CAReference.
func (in *CAReference) DeepCopy() *CAReference {
	if in == nil {
		return nil
	}
	out := new(CAReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CAResources) DeepCopyInto(out *CAResources) {
	*out = *in
	if in.Init != nil {
		in, out := &in.Init, &out.Init
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.EnrollJob != nil {
		in, out := &in.EnrollJob, &out.EnrollJob
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.HSMDaemon != nil {
		in, out := &in.HSMDaemon, &out.HSMDaemon
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CAResources.
func (in *CAResources) DeepCopy() *CAResources {
	if in == nil {
		return nil
	}
	out := new(CAResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CAStorages) DeepCopyInto(out *CAStorages) {
	*out = *in
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = new(StorageSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CAStorages.
func (in *CAStorages) DeepCopy() *CAStorages {
	if in == nil {
		return nil
	}
	out := new(CAStorages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CATLS) DeepCopyInto(out *CATLS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CATLS.
func (in *CATLS) DeepCopy() *CATLS {
	if in == nil {
		return nil
	}
	out := new(CATLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRN) DeepCopyInto(out *CRN) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRN.
func (in *CRN) DeepCopy() *CRN {
	if in == nil {
		return nil
	}
	out := new(CRN)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRStatus) DeepCopyInto(out *CRStatus) {
	*out = *in
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
	out.Versions = in.Versions
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRStatus.
func (in *CRStatus) DeepCopy() *CRStatus {
	if in == nil {
		return nil
	}
	out := new(CRStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRStatusVersion) DeepCopyInto(out *CRStatusVersion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRStatusVersion.
func (in *CRStatusVersion) DeepCopy() *CRStatusVersion {
	if in == nil {
		return nil
	}
	out := new(CRStatusVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSR) DeepCopyInto(out *CSR) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSR.
func (in *CSR) DeepCopy() *CSR {
	if in == nil {
		return nil
	}
	out := new(CSR)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ChaincodeBuilderConfig) DeepCopyInto(out *ChaincodeBuilderConfig) {
	{
		in := &in
		*out = make(ChaincodeBuilderConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChaincodeBuilderConfig.
func (in ChaincodeBuilderConfig) DeepCopy() ChaincodeBuilderConfig {
	if in == nil {
		return nil
	}
	out := new(ChaincodeBuilderConfig)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigOverride) DeepCopyInto(out *ConfigOverride) {
	*out = *in
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.TLSCA != nil {
		in, out := &in.TLSCA, &out.TLSCA
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxNameLength != nil {
		in, out := &in.MaxNameLength, &out.MaxNameLength
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigOverride.
func (in *ConfigOverride) DeepCopy() *ConfigOverride {
	if in == nil {
		return nil
	}
	out := new(ConfigOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionProfileTLS) DeepCopyInto(out *ConnectionProfileTLS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionProfileTLS.
func (in *ConnectionProfileTLS) DeepCopy() *ConnectionProfileTLS {
	if in == nil {
		return nil
	}
	out := new(ConnectionProfileTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleAction) DeepCopyInto(out *ConsoleAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleAction.
func (in *ConsoleAction) DeepCopy() *ConsoleAction {
	if in == nil {
		return nil
	}
	out := new(ConsoleAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleImages) DeepCopyInto(out *ConsoleImages) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleImages.
func (in *ConsoleImages) DeepCopy() *ConsoleImages {
	if in == nil {
		return nil
	}
	out := new(ConsoleImages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleOverrides) DeepCopyInto(out *ConsoleOverrides) {
	*out = *in
	if in.Console != nil {
		in, out := &in.Console, &out.Console
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Deployer != nil {
		in, out := &in.Deployer, &out.Deployer
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxNameLength != nil {
		in, out := &in.MaxNameLength, &out.MaxNameLength
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleOverrides.
func (in *ConsoleOverrides) DeepCopy() *ConsoleOverrides {
	if in == nil {
		return nil
	}
	out := new(ConsoleOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleOverridesConsole) DeepCopyInto(out *ConsoleOverridesConsole) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleOverridesConsole.
func (in *ConsoleOverridesConsole) DeepCopy() *ConsoleOverridesConsole {
	if in == nil {
		return nil
	}
	out := new(ConsoleOverridesConsole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleOverridesDeployer) DeepCopyInto(out *ConsoleOverridesDeployer) {
	*out = *in
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(DeployerTimeouts)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleOverridesDeployer.
func (in *ConsoleOverridesDeployer) DeepCopy() *ConsoleOverridesDeployer {
	if in == nil {
		return nil
	}
	out := new(ConsoleOverridesDeployer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleResources) DeepCopyInto(out *ConsoleResources) {
	*out = *in
	if in.Init != nil {
		in, out := &in.Init, &out.Init
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.CouchDB != nil {
		in, out := &in.CouchDB, &out.CouchDB
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Console != nil {
		in, out := &in.Console, &out.Console
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Deployer != nil {
		in, out := &in.Deployer, &out.Deployer
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Configtxlator != nil {
		in, out := &in.Configtxlator, &out.Configtxlator
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleResources.
func (in *ConsoleResources) DeepCopy() *ConsoleResources {
	if in == nil {
		return nil
	}
	out := new(ConsoleResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleStorage) DeepCopyInto(out *ConsoleStorage) {
	*out = *in
	if in.Console != nil {
		in, out := &in.Console, &out.Console
		*out = new(StorageSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleStorage.
func (in *ConsoleStorage) DeepCopy() *ConsoleStorage {
	if in == nil {
		return nil
	}
	out := new(ConsoleStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateFederation) DeepCopyInto(out *CreateFederation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateFederation.
func (in *CreateFederation) DeepCopy() *CreateFederation {
	if in == nil {
		return nil
	}
	out := new(CreateFederation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteMember) DeepCopyInto(out *DeleteMember) {
	*out = *in
	out.Member = in.Member
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteMember.
func (in *DeleteMember) DeepCopy() *DeleteMember {
	if in == nil {
		return nil
	}
	out := new(DeleteMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Deployer) DeepCopyInto(out *Deployer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Deployer.
func (in *Deployer) DeepCopy() *Deployer {
	if in == nil {
		return nil
	}
	out := new(Deployer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployerTimeouts) DeepCopyInto(out *DeployerTimeouts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployerTimeouts.
func (in *DeployerTimeouts) DeepCopy() *DeployerTimeouts {
	if in == nil {
		return nil
	}
	out := new(DeployerTimeouts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DissolveFederation) DeepCopyInto(out *DissolveFederation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DissolveFederation.
func (in *DissolveFederation) DeepCopy() *DissolveFederation {
	if in == nil {
		return nil
	}
	out := new(DissolveFederation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Enrollment) DeepCopyInto(out *Enrollment) {
	*out = *in
	if in.CATLS != nil {
		in, out := &in.CATLS, &out.CATLS
		*out = new(CATLS)
		**out = **in
	}
	if in.AdminCerts != nil {
		in, out := &in.AdminCerts, &out.AdminCerts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CSR != nil {
		in, out := &in.CSR, &out.CSR
		*out = new(CSR)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Enrollment.
func (in *Enrollment) DeepCopy() *Enrollment {
	if in == nil {
		return nil
	}
	out := new(Enrollment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnrollmentSpec) DeepCopyInto(out *EnrollmentSpec) {
	*out = *in
	if in.Component != nil {
		in, out := &in.Component, &out.Component
		*out = new(Enrollment)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(Enrollment)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientAuth != nil {
		in, out := &in.ClientAuth, &out.ClientAuth
		*out = new(Enrollment)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnrollmentSpec.
func (in *EnrollmentSpec) DeepCopy() *EnrollmentSpec {
	if in == nil {
		return nil
	}
	out := new(EnrollmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Federation) DeepCopyInto(out *Federation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Federation.
func (in *Federation) DeepCopy() *Federation {
	if in == nil {
		return nil
	}
	out := new(Federation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Federation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederationList) DeepCopyInto(out *FederationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Federation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederationList.
func (in *FederationList) DeepCopy() *FederationList {
	if in == nil {
		return nil
	}
	out := new(FederationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FederationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederationSpec) DeepCopyInto(out *FederationSpec) {
	*out = *in
	out.License = in.License
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]Member, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederationSpec.
func (in *FederationSpec) DeepCopy() *FederationSpec {
	if in == nil {
		return nil
	}
	out := new(FederationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederationStatus) DeepCopyInto(out *FederationStatus) {
	*out = *in
	in.CRStatus.DeepCopyInto(&out.CRStatus)
	if in.Networks != nil {
		in, out := &in.Networks, &out.Networks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederationStatus.
func (in *FederationStatus) DeepCopy() *FederationStatus {
	if in == nil {
		return nil
	}
	out := new(FederationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HSM) DeepCopyInto(out *HSM) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HSM.
func (in *HSM) DeepCopy() *HSM {
	if in == nil {
		return nil
	}
	out := new(HSM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPCA) DeepCopyInto(out *IBPCA) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPCA.
func (in *IBPCA) DeepCopy() *IBPCA {
	if in == nil {
		return nil
	}
	out := new(IBPCA)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IBPCA) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPCAList) DeepCopyInto(out *IBPCAList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IBPCA, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPCAList.
func (in *IBPCAList) DeepCopy() *IBPCAList {
	if in == nil {
		return nil
	}
	out := new(IBPCAList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IBPCAList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPCASpec) DeepCopyInto(out *IBPCASpec) {
	*out = *in
	out.License = in.License
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = new(CAImages)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(CAResources)
		(*in).DeepCopyInto(*out)
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(Service)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(CAStorages)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigOverride != nil {
		in, out := &in.ConfigOverride, &out.ConfigOverride
		*out = new(ConfigOverride)
		(*in).DeepCopyInto(*out)
	}
	if in.HSM != nil {
		in, out := &in.HSM, &out.HSM
		*out = new(HSM)
		**out = **in
	}
	out.CustomNames = in.CustomNames
	out.Ingress = in.Ingress
	if in.Arch != nil {
		in, out := &in.Arch, &out.Arch
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Action = in.Action
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPCASpec.
func (in *IBPCASpec) DeepCopy() *IBPCASpec {
	if in == nil {
		return nil
	}
	out := new(IBPCASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPCAStatus) DeepCopyInto(out *IBPCAStatus) {
	*out = *in
	in.CRStatus.DeepCopyInto(&out.CRStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPCAStatus.
func (in *IBPCAStatus) DeepCopy() *IBPCAStatus {
	if in == nil {
		return nil
	}
	out := new(IBPCAStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPConsole) DeepCopyInto(out *IBPConsole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPConsole.
func (in *IBPConsole) DeepCopy() *IBPConsole {
	if in == nil {
		return nil
	}
	out := new(IBPConsole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IBPConsole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPConsoleList) DeepCopyInto(out *IBPConsoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IBPConsole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPConsoleList.
func (in *IBPConsoleList) DeepCopy() *IBPConsoleList {
	if in == nil {
		return nil
	}
	out := new(IBPConsoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IBPConsoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPConsoleSpec) DeepCopyInto(out *IBPConsoleSpec) {
	*out = *in
	out.License = in.License
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = new(ConsoleImages)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ConsoleResources)
		(*in).DeepCopyInto(*out)
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(Service)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(ConsoleStorage)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkInfo != nil {
		in, out := &in.NetworkInfo, &out.NetworkInfo
		*out = new(NetworkInfo)
		**out = **in
	}
	out.Ingress = in.Ingress
	if in.ClusterData != nil {
		in, out := &in.ClusterData, &out.ClusterData
		*out = new(consolev1.IBPConsoleClusterData)
		(*in).DeepCopyInto(*out)
	}
	if in.FeatureFlags != nil {
		in, out := &in.FeatureFlags, &out.FeatureFlags
		*out = new(consolev1.FeatureFlags)
		(*in).DeepCopyInto(*out)
	}
	if in.IBMID != nil {
		in, out := &in.IBMID, &out.IBMID
		*out = new(consolev1.IBMID)
		**out = **in
	}
	if in.Proxying != nil {
		in, out := &in.Proxying, &out.Proxying
		*out = new(bool)
		**out = **in
	}
	if in.CRN != nil {
		in, out := &in.CRN, &out.CRN
		*out = new(CRN)
		**out = **in
	}
	if in.Kubeconfig != nil {
		in, out := &in.Kubeconfig, &out.Kubeconfig
		*out = new([]byte)
		if **in != nil {
			in, out := *in, *out
			*out = make([]byte, len(*in))
			copy(*out, *in)
		}
	}
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = new(Versions)
		(*in).DeepCopyInto(*out)
	}
	if in.Deployer != nil {
		in, out := &in.Deployer, &out.Deployer
		*out = new(Deployer)
		**out = **in
	}
	if in.Arch != nil {
		in, out := &in.Arch, &out.Arch
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConfigOverride != nil {
		in, out := &in.ConfigOverride, &out.ConfigOverride
		*out = new(ConsoleOverrides)
		(*in).DeepCopyInto(*out)
	}
	out.Action = in.Action
	if in.UseTags != nil {
		in, out := &in.UseTags, &out.UseTags
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPConsoleSpec.
func (in *IBPConsoleSpec) DeepCopy() *IBPConsoleSpec {
	if in == nil {
		return nil
	}
	out := new(IBPConsoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPConsoleStatus) DeepCopyInto(out *IBPConsoleStatus) {
	*out = *in
	in.CRStatus.DeepCopyInto(&out.CRStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPConsoleStatus.
func (in *IBPConsoleStatus) DeepCopy() *IBPConsoleStatus {
	if in == nil {
		return nil
	}
	out := new(IBPConsoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPOrderer) DeepCopyInto(out *IBPOrderer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPOrderer.
func (in *IBPOrderer) DeepCopy() *IBPOrderer {
	if in == nil {
		return nil
	}
	out := new(IBPOrderer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IBPOrderer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPOrdererClusterLocation) DeepCopyInto(out *IBPOrdererClusterLocation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPOrdererClusterLocation.
func (in *IBPOrdererClusterLocation) DeepCopy() *IBPOrdererClusterLocation {
	if in == nil {
		return nil
	}
	out := new(IBPOrdererClusterLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPOrdererList) DeepCopyInto(out *IBPOrdererList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IBPOrderer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPOrdererList.
func (in *IBPOrdererList) DeepCopy() *IBPOrdererList {
	if in == nil {
		return nil
	}
	out := new(IBPOrdererList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IBPOrdererList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPOrdererSpec) DeepCopyInto(out *IBPOrdererSpec) {
	*out = *in
	out.License = in.License
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = new(OrdererImages)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(OrdererResources)
		(*in).DeepCopyInto(*out)
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(Service)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(OrdererStorages)
		(*in).DeepCopyInto(*out)
	}
	if in.UseChannelLess != nil {
		in, out := &in.UseChannelLess, &out.UseChannelLess
		*out = new(bool)
		**out = **in
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(SecretSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigOverride != nil {
		in, out := &in.ConfigOverride, &out.ConfigOverride
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.HSM != nil {
		in, out := &in.HSM, &out.HSM
		*out = new(HSM)
		**out = **in
	}
	if in.IsPrecreate != nil {
		in, out := &in.IsPrecreate, &out.IsPrecreate
		*out = new(bool)
		**out = **in
	}
	if in.ClusterLocation != nil {
		in, out := &in.ClusterLocation, &out.ClusterLocation
		*out = make([]IBPOrdererClusterLocation, len(*in))
		copy(*out, *in)
	}
	if in.ClusterConfigOverride != nil {
		in, out := &in.ClusterConfigOverride, &out.ClusterConfigOverride
		*out = make([]*runtime.RawExtension, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(runtime.RawExtension)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ClusterSecret != nil {
		in, out := &in.ClusterSecret, &out.ClusterSecret
		*out = make([]*SecretSpec, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(SecretSpec)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.NodeNumber != nil {
		in, out := &in.NodeNumber, &out.NodeNumber
		*out = new(int)
		**out = **in
	}
	out.Ingress = in.Ingress
	if in.Arch != nil {
		in, out := &in.Arch, &out.Arch
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DisableNodeOU != nil {
		in, out := &in.DisableNodeOU, &out.DisableNodeOU
		*out = new(bool)
		**out = **in
	}
	out.CustomNames = in.CustomNames
	out.Action = in.Action
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPOrdererSpec.
func (in *IBPOrdererSpec) DeepCopy() *IBPOrdererSpec {
	if in == nil {
		return nil
	}
	out := new(IBPOrdererSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPOrdererStatus) DeepCopyInto(out *IBPOrdererStatus) {
	*out = *in
	in.CRStatus.DeepCopyInto(&out.CRStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPOrdererStatus.
func (in *IBPOrdererStatus) DeepCopy() *IBPOrdererStatus {
	if in == nil {
		return nil
	}
	out := new(IBPOrdererStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPPeer) DeepCopyInto(out *IBPPeer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPPeer.
func (in *IBPPeer) DeepCopy() *IBPPeer {
	if in == nil {
		return nil
	}
	out := new(IBPPeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IBPPeer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPPeerList) DeepCopyInto(out *IBPPeerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IBPPeer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPPeerList.
func (in *IBPPeerList) DeepCopy() *IBPPeerList {
	if in == nil {
		return nil
	}
	out := new(IBPPeerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IBPPeerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPPeerSpec) DeepCopyInto(out *IBPPeerSpec) {
	*out = *in
	out.License = in.License
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = new(PeerImages)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(PeerResources)
		(*in).DeepCopyInto(*out)
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(Service)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(PeerStorages)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigOverride != nil {
		in, out := &in.ConfigOverride, &out.ConfigOverride
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.HSM != nil {
		in, out := &in.HSM, &out.HSM
		*out = new(HSM)
		**out = **in
	}
	if in.DisableNodeOU != nil {
		in, out := &in.DisableNodeOU, &out.DisableNodeOU
		*out = new(bool)
		**out = **in
	}
	out.CustomNames = in.CustomNames
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(SecretSpec)
		(*in).DeepCopyInto(*out)
	}
	out.Ingress = in.Ingress
	if in.Arch != nil {
		in, out := &in.Arch, &out.Arch
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DindArgs != nil {
		in, out := &in.DindArgs, &out.DindArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Action = in.Action
	if in.ChaincodeBuilderConfig != nil {
		in, out := &in.ChaincodeBuilderConfig, &out.ChaincodeBuilderConfig
		*out = make(ChaincodeBuilderConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPPeerSpec.
func (in *IBPPeerSpec) DeepCopy() *IBPPeerSpec {
	if in == nil {
		return nil
	}
	out := new(IBPPeerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBPPeerStatus) DeepCopyInto(out *IBPPeerStatus) {
	*out = *in
	in.CRStatus.DeepCopyInto(&out.CRStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBPPeerStatus.
func (in *IBPPeerStatus) DeepCopy() *IBPPeerStatus {
	if in == nil {
		return nil
	}
	out := new(IBPPeerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ingress) DeepCopyInto(out *Ingress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ingress.
func (in *Ingress) DeepCopy() *Ingress {
	if in == nil {
		return nil
	}
	out := new(Ingress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *License) DeepCopyInto(out *License) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new License.
func (in *License) DeepCopy() *License {
	if in == nil {
		return nil
	}
	out := new(License)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MSP) DeepCopyInto(out *MSP) {
	*out = *in
	if in.CACerts != nil {
		in, out := &in.CACerts, &out.CACerts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IntermediateCerts != nil {
		in, out := &in.IntermediateCerts, &out.IntermediateCerts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdminCerts != nil {
		in, out := &in.AdminCerts, &out.AdminCerts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MSP.
func (in *MSP) DeepCopy() *MSP {
	if in == nil {
		return nil
	}
	out := new(MSP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MSPSpec) DeepCopyInto(out *MSPSpec) {
	*out = *in
	if in.Component != nil {
		in, out := &in.Component, &out.Component
		*out = new(MSP)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(MSP)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientAuth != nil {
		in, out := &in.ClientAuth, &out.ClientAuth
		*out = new(MSP)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MSPSpec.
func (in *MSPSpec) DeepCopy() *MSPSpec {
	if in == nil {
		return nil
	}
	out := new(MSPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Member) DeepCopyInto(out *Member) {
	*out = *in
	out.NamespacedName = in.NamespacedName
	in.JoinedAt.DeepCopyInto(&out.JoinedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Member.
func (in *Member) DeepCopy() *Member {
	if in == nil {
		return nil
	}
	out := new(Member)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedName) DeepCopyInto(out *NamespacedName) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedName.
func (in *NamespacedName) DeepCopy() *NamespacedName {
	if in == nil {
		return nil
	}
	out := new(NamespacedName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Network) DeepCopyInto(out *Network) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Network.
func (in *Network) DeepCopy() *Network {
	if in == nil {
		return nil
	}
	out := new(Network)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Network) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInfo) DeepCopyInto(out *NetworkInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInfo.
func (in *NetworkInfo) DeepCopy() *NetworkInfo {
	if in == nil {
		return nil
	}
	out := new(NetworkInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkList) DeepCopyInto(out *NetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Network, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkList.
func (in *NetworkList) DeepCopy() *NetworkList {
	if in == nil {
		return nil
	}
	out := new(NetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSpec) DeepCopyInto(out *NetworkSpec) {
	*out = *in
	out.License = in.License
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]Member, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.OrderSpec.DeepCopyInto(&out.OrderSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSpec.
func (in *NetworkSpec) DeepCopy() *NetworkSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkStatus) DeepCopyInto(out *NetworkStatus) {
	*out = *in
	in.CRStatus.DeepCopyInto(&out.CRStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkStatus.
func (in *NetworkStatus) DeepCopy() *NetworkStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrdererAction) DeepCopyInto(out *OrdererAction) {
	*out = *in
	out.Reenroll = in.Reenroll
	out.Enroll = in.Enroll
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrdererAction.
func (in *OrdererAction) DeepCopy() *OrdererAction {
	if in == nil {
		return nil
	}
	out := new(OrdererAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrdererConnectionProfile) DeepCopyInto(out *OrdererConnectionProfile) {
	*out = *in
	out.Endpoints = in.Endpoints
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(MSP)
		(*in).DeepCopyInto(*out)
	}
	if in.Component != nil {
		in, out := &in.Component, &out.Component
		*out = new(MSP)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrdererConnectionProfile.
func (in *OrdererConnectionProfile) DeepCopy() *OrdererConnectionProfile {
	if in == nil {
		return nil
	}
	out := new(OrdererConnectionProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrdererCustomNames) DeepCopyInto(out *OrdererCustomNames) {
	*out = *in
	out.PVC = in.PVC
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrdererCustomNames.
func (in *OrdererCustomNames) DeepCopy() *OrdererCustomNames {
	if in == nil {
		return nil
	}
	out := new(OrdererCustomNames)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrdererEndpoints) DeepCopyInto(out *OrdererEndpoints) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrdererEndpoints.
func (in *OrdererEndpoints) DeepCopy() *OrdererEndpoints {
	if in == nil {
		return nil
	}
	out := new(OrdererEndpoints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrdererEnrollAction) DeepCopyInto(out *OrdererEnrollAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrdererEnrollAction.
func (in *OrdererEnrollAction) DeepCopy() *OrdererEnrollAction {
	if in == nil {
		return nil
	}
	out := new(OrdererEnrollAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrdererImages) DeepCopyInto(out *OrdererImages) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrdererImages.
func (in *OrdererImages) DeepCopy() *OrdererImages {
	if in == nil {
		return nil
	}
	out := new(OrdererImages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrdererPVCNames) DeepCopyInto(out *OrdererPVCNames) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrdererPVCNames.
func (in *OrdererPVCNames) DeepCopy() *OrdererPVCNames {
	if in == nil {
		return nil
	}
	out := new(OrdererPVCNames)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrdererReenrollAction) DeepCopyInto(out *OrdererReenrollAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrdererReenrollAction.
func (in *OrdererReenrollAction) DeepCopy() *OrdererReenrollAction {
	if in == nil {
		return nil
	}
	out := new(OrdererReenrollAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrdererResources) DeepCopyInto(out *OrdererResources) {
	*out = *in
	if in.Init != nil {
		in, out := &in.Init, &out.Init
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Orderer != nil {
		in, out := &in.Orderer, &out.Orderer
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.GRPCProxy != nil {
		in, out := &in.GRPCProxy, &out.GRPCProxy
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Enroller != nil {
		in, out := &in.Enroller, &out.Enroller
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.HSMDaemon != nil {
		in, out := &in.HSMDaemon, &out.HSMDaemon
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrdererResources.
func (in *OrdererResources) DeepCopy() *OrdererResources {
	if in == nil {
		return nil
	}
	out := new(OrdererResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrdererStorages) DeepCopyInto(out *OrdererStorages) {
	*out = *in
	if in.Orderer != nil {
		in, out := &in.Orderer, &out.Orderer
		*out = new(StorageSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrdererStorages.
func (in *OrdererStorages) DeepCopy() *OrdererStorages {
	if in == nil {
		return nil
	}
	out := new(OrdererStorages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Organization) DeepCopyInto(out *Organization) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Organization.
func (in *Organization) DeepCopy() *Organization {
	if in == nil {
		return nil
	}
	out := new(Organization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Organization) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationList) DeepCopyInto(out *OrganizationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Organization, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationList.
func (in *OrganizationList) DeepCopy() *OrganizationList {
	if in == nil {
		return nil
	}
	out := new(OrganizationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrganizationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationSpec) DeepCopyInto(out *OrganizationSpec) {
	*out = *in
	out.License = in.License
	if in.Clients != nil {
		in, out := &in.Clients, &out.Clients
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.CASpec.DeepCopyInto(&out.CASpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationSpec.
func (in *OrganizationSpec) DeepCopy() *OrganizationSpec {
	if in == nil {
		return nil
	}
	out := new(OrganizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationStatus) DeepCopyInto(out *OrganizationStatus) {
	*out = *in
	in.CRStatus.DeepCopyInto(&out.CRStatus)
	if in.Federations != nil {
		in, out := &in.Federations, &out.Federations
		*out = make([]NamespacedName, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationStatus.
func (in *OrganizationStatus) DeepCopy() *OrganizationStatus {
	if in == nil {
		return nil
	}
	out := new(OrganizationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerAction) DeepCopyInto(out *PeerAction) {
	*out = *in
	out.Reenroll = in.Reenroll
	out.Enroll = in.Enroll
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerAction.
func (in *PeerAction) DeepCopy() *PeerAction {
	if in == nil {
		return nil
	}
	out := new(PeerAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerConnectionProfile) DeepCopyInto(out *PeerConnectionProfile) {
	*out = *in
	out.Endpoints = in.Endpoints
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(MSP)
		(*in).DeepCopyInto(*out)
	}
	if in.Component != nil {
		in, out := &in.Component, &out.Component
		*out = new(MSP)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerConnectionProfile.
func (in *PeerConnectionProfile) DeepCopy() *PeerConnectionProfile {
	if in == nil {
		return nil
	}
	out := new(PeerConnectionProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerCustomNames) DeepCopyInto(out *PeerCustomNames) {
	*out = *in
	out.PVC = in.PVC
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerCustomNames.
func (in *PeerCustomNames) DeepCopy() *PeerCustomNames {
	if in == nil {
		return nil
	}
	out := new(PeerCustomNames)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerEndpoints) DeepCopyInto(out *PeerEndpoints) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerEndpoints.
func (in *PeerEndpoints) DeepCopy() *PeerEndpoints {
	if in == nil {
		return nil
	}
	out := new(PeerEndpoints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerEnrollAction) DeepCopyInto(out *PeerEnrollAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerEnrollAction.
func (in *PeerEnrollAction) DeepCopy() *PeerEnrollAction {
	if in == nil {
		return nil
	}
	out := new(PeerEnrollAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerImages) DeepCopyInto(out *PeerImages) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerImages.
func (in *PeerImages) DeepCopy() *PeerImages {
	if in == nil {
		return nil
	}
	out := new(PeerImages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerPVCNames) DeepCopyInto(out *PeerPVCNames) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerPVCNames.
func (in *PeerPVCNames) DeepCopy() *PeerPVCNames {
	if in == nil {
		return nil
	}
	out := new(PeerPVCNames)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerReenrollAction) DeepCopyInto(out *PeerReenrollAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerReenrollAction.
func (in *PeerReenrollAction) DeepCopy() *PeerReenrollAction {
	if in == nil {
		return nil
	}
	out := new(PeerReenrollAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerResources) DeepCopyInto(out *PeerResources) {
	*out = *in
	if in.Init != nil {
		in, out := &in.Init, &out.Init
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Peer != nil {
		in, out := &in.Peer, &out.Peer
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.GRPCProxy != nil {
		in, out := &in.GRPCProxy, &out.GRPCProxy
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.FluentD != nil {
		in, out := &in.FluentD, &out.FluentD
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.DinD != nil {
		in, out := &in.DinD, &out.DinD
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.CouchDB != nil {
		in, out := &in.CouchDB, &out.CouchDB
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.CCLauncher != nil {
		in, out := &in.CCLauncher, &out.CCLauncher
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Enroller != nil {
		in, out := &in.Enroller, &out.Enroller
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.HSMDaemon != nil {
		in, out := &in.HSMDaemon, &out.HSMDaemon
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerResources.
func (in *PeerResources) DeepCopy() *PeerResources {
	if in == nil {
		return nil
	}
	out := new(PeerResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerStorages) DeepCopyInto(out *PeerStorages) {
	*out = *in
	if in.StateDB != nil {
		in, out := &in.StateDB, &out.StateDB
		*out = new(StorageSpec)
		**out = **in
	}
	if in.Peer != nil {
		in, out := &in.Peer, &out.Peer
		*out = new(StorageSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerStorages.
func (in *PeerStorages) DeepCopy() *PeerStorages {
	if in == nil {
		return nil
	}
	out := new(PeerStorages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Proposal) DeepCopyInto(out *Proposal) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Proposal.
func (in *Proposal) DeepCopy() *Proposal {
	if in == nil {
		return nil
	}
	out := new(Proposal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Proposal) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProposalCondition) DeepCopyInto(out *ProposalCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProposalCondition.
func (in *ProposalCondition) DeepCopy() *ProposalCondition {
	if in == nil {
		return nil
	}
	out := new(ProposalCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProposalList) DeepCopyInto(out *ProposalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Proposal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProposalList.
func (in *ProposalList) DeepCopy() *ProposalList {
	if in == nil {
		return nil
	}
	out := new(ProposalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProposalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProposalSource) DeepCopyInto(out *ProposalSource) {
	*out = *in
	if in.CreateFederation != nil {
		in, out := &in.CreateFederation, &out.CreateFederation
		*out = new(CreateFederation)
		**out = **in
	}
	if in.AddMember != nil {
		in, out := &in.AddMember, &out.AddMember
		*out = new(AddMember)
		(*in).DeepCopyInto(*out)
	}
	if in.DeleteMember != nil {
		in, out := &in.DeleteMember, &out.DeleteMember
		*out = new(DeleteMember)
		**out = **in
	}
	if in.DissolveFederation != nil {
		in, out := &in.DissolveFederation, &out.DissolveFederation
		*out = new(DissolveFederation)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProposalSource.
func (in *ProposalSource) DeepCopy() *ProposalSource {
	if in == nil {
		return nil
	}
	out := new(ProposalSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProposalSpec) DeepCopyInto(out *ProposalSpec) {
	*out = *in
	out.Initiator = in.Initiator
	in.ProposalSource.DeepCopyInto(&out.ProposalSource)
	in.StartAt.DeepCopyInto(&out.StartAt)
	in.EndAt.DeepCopyInto(&out.EndAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProposalSpec.
func (in *ProposalSpec) DeepCopy() *ProposalSpec {
	if in == nil {
		return nil
	}
	out := new(ProposalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProposalStatus) DeepCopyInto(out *ProposalStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ProposalCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Votes != nil {
		in, out := &in.Votes, &out.Votes
		*out = make([]VoteResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProposalStatus.
func (in *ProposalStatus) DeepCopy() *ProposalStatus {
	if in == nil {
		return nil
	}
	out := new(ProposalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Renew) DeepCopyInto(out *Renew) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Renew.
func (in *Renew) DeepCopy() *Renew {
	if in == nil {
		return nil
	}
	out := new(Renew)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretSpec) DeepCopyInto(out *SecretSpec) {
	*out = *in
	if in.Enrollment != nil {
		in, out := &in.Enrollment, &out.Enrollment
		*out = new(EnrollmentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MSP != nil {
		in, out := &in.MSP, &out.MSP
		*out = new(MSPSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretSpec.
func (in *SecretSpec) DeepCopy() *SecretSpec {
	if in == nil {
		return nil
	}
	out := new(SecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Service) DeepCopyInto(out *Service) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Service.
func (in *Service) DeepCopy() *Service {
	if in == nil {
		return nil
	}
	out := new(Service)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionCA) DeepCopyInto(out *VersionCA) {
	*out = *in
	out.Image = in.Image
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionCA.
func (in *VersionCA) DeepCopy() *VersionCA {
	if in == nil {
		return nil
	}
	out := new(VersionCA)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionOrderer) DeepCopyInto(out *VersionOrderer) {
	*out = *in
	out.Image = in.Image
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionOrderer.
func (in *VersionOrderer) DeepCopy() *VersionOrderer {
	if in == nil {
		return nil
	}
	out := new(VersionOrderer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionPeer) DeepCopyInto(out *VersionPeer) {
	*out = *in
	out.Image = in.Image
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionPeer.
func (in *VersionPeer) DeepCopy() *VersionPeer {
	if in == nil {
		return nil
	}
	out := new(VersionPeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Versions) DeepCopyInto(out *Versions) {
	*out = *in
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = make(map[string]VersionCA, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Peer != nil {
		in, out := &in.Peer, &out.Peer
		*out = make(map[string]VersionPeer, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Orderer != nil {
		in, out := &in.Orderer, &out.Orderer
		*out = make(map[string]VersionOrderer, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Versions.
func (in *Versions) DeepCopy() *Versions {
	if in == nil {
		return nil
	}
	out := new(Versions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Vote) DeepCopyInto(out *Vote) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Vote.
func (in *Vote) DeepCopy() *Vote {
	if in == nil {
		return nil
	}
	out := new(Vote)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Vote) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VoteList) DeepCopyInto(out *VoteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Vote, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VoteList.
func (in *VoteList) DeepCopy() *VoteList {
	if in == nil {
		return nil
	}
	out := new(VoteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VoteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VoteResult) DeepCopyInto(out *VoteResult) {
	*out = *in
	out.NamespacedName = in.NamespacedName
	out.Organization = in.Organization
	if in.Decision != nil {
		in, out := &in.Decision, &out.Decision
		*out = new(bool)
		**out = **in
	}
	in.VoteTime.DeepCopyInto(&out.VoteTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VoteResult.
func (in *VoteResult) DeepCopy() *VoteResult {
	if in == nil {
		return nil
	}
	out := new(VoteResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VoteSpec) DeepCopyInto(out *VoteSpec) {
	*out = *in
	if in.Decision != nil {
		in, out := &in.Decision, &out.Decision
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VoteSpec.
func (in *VoteSpec) DeepCopy() *VoteSpec {
	if in == nil {
		return nil
	}
	out := new(VoteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VoteStatus) DeepCopyInto(out *VoteStatus) {
	*out = *in
	in.VoteTime.DeepCopyInto(&out.VoteTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VoteStatus.
func (in *VoteStatus) DeepCopy() *VoteStatus {
	if in == nil {
		return nil
	}
	out := new(VoteStatus)
	in.DeepCopyInto(out)
	return out
}
